# config.toml

[theme]
# A modern, robust color palette for better readability
base = "light"
primaryColor = "#0d6efd"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f9fc"
textColor = "#31333F"
font = "sans serif"

[server]
runOnSave = true